# Generated by Django 6.0.6 on 2026-09-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('learning', '0002_alter_reviewitem_mastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField(help_text='The factual claim: "React uses virtual DOM for efficient updates"')),
                ('evidence_text', models.TextField(help_text='Direct quote from the source document supporting this claim')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='learning.topicmastery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'topic'], name='graph_claim_user_id_9731cc_idx'), models.Index(fields=['content_type', 'object_id'], name='graph_claim_content_671243_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopicRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PREREQ', 'Is Prerequisite For'), ('RELATED', 'Is Related To')], max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='AI confidence score (0.0 to 1.0)')),
                ('relationship_reason', models.TextField(blank=True, default='', help_text='AI-generated explanation: "B requires A because concept X from A is needed to understand Y in B"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_topic', models.ForeignKey(help_text='The prerequisite / source topic', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='learning.topicmastery')),
                ('target_topic', models.ForeignKey(help_text='The topic that depends on / is related to the source', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='learning.topicmastery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'relationship_type'], name='graph_topic_user_id_c02753_idx')],
                'unique_together': {('source_topic', 'target_topic', 'relationship_type')},
            },
        ),
    ]
