# Generated by Django 6.0.6 on 2026-07-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting Text'), ('chunking', 'Chunking'), ('embedding', 'Generating Embeddings'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
