# Generated by Django 6.0.6 on 2026-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_error_message_note_failed_at_note_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='processing_status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('pending', 'Pending'), ('extracting', 'Extracting Text'), ('chunking', 'Chunking'), ('embedding', 'Generating Embeddings'), ('completed', 'Completed'), ('failed', 'Failed')], default='unprocessed', max_length=20),
        ),
    ]
