# Generated by Django 6.0.6 on 2026-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='extract_topics',
            field=models.BooleanField(default=True, help_text='If True, AI will extract topics for spaced repetition.'),
        ),
    ]
