# Generated by Django 6.0.6 on 2026-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_extract_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='extract_topics',
            field=models.BooleanField(default=False, help_text='If True, AI will extract topics for spaced repetition.'),
        ),
    ]
