# Generated by Django 6.0.6 on 2026-08-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('correct_items', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('confidence_level', models.FloatField(default=0.0)),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('review_interval_days', models.IntegerField(default=1)),
                ('next_review_date', models.DateField()),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('consecutive_correct', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('weak_sub_concepts', models.JSONField(blank=True, default=list, help_text='List of specific sub-concepts the user struggles with')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='MCQ options: {"A": "...", "B": "...", "C": "...", "D": "..."}')),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField()),
                ('review_context', models.TextField(help_text='"Why am I reviewing this?" — generated from TopicMastery metadata')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('user_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.reviewsession')),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='learning.topicmastery')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TopicSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='learning.topicmastery')),
            ],
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['user', 'next_review_date'], name='learning_to_user_id_c5691b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicmastery',
            unique_together={('user', 'topic_name')},
        ),
        migrations.AddIndex(
            model_name='topicsource',
            index=models.Index(fields=['content_type', 'object_id'], name='learning_to_content_cada8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topicsource',
            unique_together={('topic', 'content_type', 'object_id')},
        ),
    ]
