# Generated by Django 6.0.6 on 2026-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
