# Generated by Django 6.0.6 on 2026-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_document_extract_topics_resource_extract_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extract_topics',
            field=models.BooleanField(default=False, help_text='If True, AI will extract topics for spaced repetition.'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='extract_topics',
            field=models.BooleanField(default=False, help_text='If True, AI will extract topics for spaced repetition.'),
        ),
    ]
