from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class TopicMastery(models.Model):
    """
    Tracks a user's mastery of a specific topic.
    Topics are auto-extracted from Documents/Notes during the RAG pipeline.
    SM-2 spaced repetition algorithm manages review scheduling.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='topic_masteries'
    )
    topic_name = models.CharField(max_length=200)

    # --- SM-2 Algorithm Fields ---
    confidence_level = models.FloatField(default=0.0)          # 0.0 to 1.0
    easiness_factor = models.FloatField(default=2.5)           # SM-2 EF (min 1.3)
    review_interval_days = models.IntegerField(default=1)      # Current interval between reviews
    next_review_date = models.DateField()                      # When to review next
    last_reviewed = models.DateTimeField(null=True, blank=True)
    consecutive_correct = models.IntegerField(default=0)

    # --- Performance Tracking ---
    total_reviews = models.IntegerField(default=0)
    total_correct = models.IntegerField(default=0)

    # --- Weak Area Tracking ---
    weak_sub_concepts = models.JSONField(
        default=list, blank=True,
        help_text='List of specific sub-concepts the user struggles with'
    )
    # Example: ["useEffect cleanup", "dependency array rules"]

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ['user', 'topic_name']
        ordering = ['next_review_date']
        indexes = [
            models.Index(fields=['user', 'next_review_date']),
        ]

    def __str__(self):
        return f"{self.topic_name} ({self.confidence_level:.0%}) - {self.user.username}"

    @property
    def accuracy(self):
        """Returns accuracy percentage based on total reviews."""
        if self.total_reviews == 0:
            return 0.0
        return self.total_correct / self.total_reviews


class TopicSource(models.Model):
    """
    Links a TopicMastery to its source Document or Note.
    Uses GenericForeignKey so a topic can come from any content type.
    """
    topic = models.ForeignKey(
        TopicMastery,
        on_delete=models.CASCADE,
        related_name='sources'
    )
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    source = GenericForeignKey('content_type', 'object_id')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['topic', 'content_type', 'object_id']
        indexes = [
            models.Index(fields=['content_type', 'object_id']),
        ]

    def __str__(self):
        return f"{self.topic.topic_name} ← {self.content_type.model}:{self.object_id}"


class ReviewSession(models.Model):
    """
    A single daily review session.
    Contains multiple ReviewItems (questions) that the user answers.
    """
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='review_sessions'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    score = models.FloatField(null=True, blank=True)       # Percentage correct (0-100)
    total_items = models.IntegerField(default=0)
    correct_items = models.IntegerField(default=0)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        status = "Completed" if self.completed_at else "In Progress"
        return f"Review {self.created_at.strftime('%Y-%m-%d')} - {status}"


class ReviewItem(models.Model):
    """
    A single question within a review session.
    Generated by Gemini based on the topic's source chunks.
    """
    class Difficulty(models.IntegerChoices):
        EASY = 1, 'Easy'
        MEDIUM = 2, 'Medium'
        HARD = 3, 'Hard'

    session = models.ForeignKey(
        ReviewSession,
        on_delete=models.CASCADE,
        related_name='items'
    )
    mastery = models.ForeignKey(
        TopicMastery,
        on_delete=models.CASCADE,
        related_name='review_items'
    )

    # --- Question Content (generated by Gemini) ---
    question_text = models.TextField()
    options = models.JSONField(
        help_text='MCQ options: {"A": "...", "B": "...", "C": "...", "D": "..."}'
    )
    correct_answer = models.CharField(max_length=1)        # "A", "B", "C", or "D"
    explanation = models.TextField()                        # AI explanation of the answer

    # --- Context & Difficulty ---
    review_context = models.TextField(
        help_text='"Why am I reviewing this?" — generated from TopicMastery metadata'
    )
    difficulty_level = models.IntegerField(choices=Difficulty.choices)

    # --- User Response ---
    user_answer = models.CharField(max_length=1, null=True, blank=True)
    is_correct = models.BooleanField(null=True)
    answered_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        status = "✓" if self.is_correct else ("✗" if self.is_correct is False else "?")
        return f"[{status}] {self.mastery.topic_name}"
